services:
    gateway:
        image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/html:/var/www/html:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - api

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
        restart: always
            
    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}
        restart: always

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_DEBUG: 0
            DB_URL: postgres://app:${API_DB_PASSWORD}@api-postgres:54321/app

    api-php-cli:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        restart: always
        environment:
            APP_DEBUG: 0
            DB_URL: postgres://app:${API_DB_PASSWORD}@api-postgres:54321/app

    api-postgres:
        image: postgres:17.4-alpine3.21
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - auction-postgres-data:/var/lib/postgresql/data
        networks:
            - auction-network

volumes:
    auction-postgres-data:
