services:
    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/DockerFile
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.auction.rule=Host(`auction.localhost`) || Host(`www.auction.localhost`)
            - traefik.http.routers.auction.entryPoints=http
            - traefik.http.services.auction.loadBalancer.server.port=80
            - traefik.http.middlewares.auction-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
            - traefik.http.middlewares.auction-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.auction-redirect.redirectRegex.permanent=true
            - traefik.http.routers.auction.middlewares=auction-redirect
            
    api:
        build: 
            context: api/docker
            dockerfile: development/nginx/DockerFile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api-auction.rule=Host(`api.auction.localhost`)
            - traefik.http.routers.api-auction.entryPoints=http
            - traefik.http.services.api-auction.loadBalancer.server.port=80

    api-php-fpm:
        build: 
            context: api/docker
            dockerfile: development/php-fpm/DockerFile
        extra_hosts:
            - "host.docker.internal:192.168.0.11"
        volumes:
            - ./api:/app:cached
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            DB_HOST: api-postgres
            DB_PORT: 5432
            DB_NAME: app
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            XDEBUG_MODE: debug
            XDEBUG_CLIENT_HOST: host.docker.internal
            XDEBUG_CLIENT_PORT: 9003
            PHP_IDE_CONFIG: "serverName=app-server"

    api-php-cli:
        build: 
            context: api/docker
            dockerfile: development/php-cli/DockerFile
        extra_hosts:
            - "host.docker.internal:192.168.0.11"
        volumes:
            - /home/rebit-pro/auction/api:/app:cached
        ports:
            - "9003:9003"
        working_dir: /app  # Ключевая строка!
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            DB_HOST: api-postgres
            DB_PORT: 5432
            DB_NAME: app
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            XDEBUG_MODE: debug
            XDEBUG_CLIENT_HOST: host.docker.internal
            XDEBUG_CLIENT_PORT: 9003
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}

    api-postgres:
        image: postgres:17.4-alpine3.21
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secrets
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres:

networks:
    traefik-public:
        external: true