FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libonig-dev \
    libicu-dev \
    libxml2-dev \
    libpq-dev \
    curl \
    libldap2-dev \
    unzip \
    git \
    gnupg2 \
    postgresql-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        gd \
        bcmath \
        exif \
        mysqli \
        opcache \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        intl \
        soap \
        sockets \
        zip \
    && pecl install memcache xdebug \
    && docker-php-ext-enable memcache xdebug \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini

COPY ./common/php/conf.d /usr/local/etc/php/conf.d
COPY ./development/php/conf.d /usr/local/etc/php/conf.d

ENV COMPOSER_ALLOW_SUPERUSER 1

# Установите Composer в /usr/local/bin
RUN curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer --version=2.8.0 \
    && chmod +x /usr/local/bin/composer

# Добавьте пути в переменную окружения
ENV PATH="/usr/local/bin:/usr/bin:${PATH}"

# Настройка пользователя
RUN useradd -m -s /bin/bash rebit-pro && \
    mkdir -p /app && \
    chown -R rebit-pro:rebit-pro /app

WORKDIR /app